spring:
  datasource:
    url: jdbc:mysql:///dd_driving?serverTimezone=UTC
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver
#  redis:
#    host: localhost
#    port: 6379
#    jedis:
#      pool:
#        max-idle: 8
#        max-wait: 1000
#    database: 2
server:
  port: 8090
#spring:
#  datasource:
#    url: jdbc:postgresql://localhost:5432/dd_user
#    username: postgres
#    password: root
##    type: com.alibaba.druid.pool.DruidDataSource
#    driver-class-name: org.postgresql.Driver
#postgresql